exclude: "lib/.*"
repos:
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: "v3.1.0" # Use the sha or tag you want to point at
      hooks:
          - id: prettier
            files: \.ts$
    - repo: https://github.com/pre-commit/mirrors-eslint
      rev: "v8.56.0" # Use the sha / tag you want to point at
      hooks:
          - id: eslint
            files: \.ts$ # *.js, *.jsx, *.ts and *.tsx
            types: [file]
    - repo: https://github.com/hato1883/mirrors-jest-custom
      rev: "v1.0.0" # Use the sha / tag you want to point at
      hooks:
          - id: jest
            files: \.ts$ # *.js, *.jsx, *.ts and *.tsx
            types: [file]
